### ISSUE TITLE
Scaling issues

### ISSUE THREAD

**Issue by ElPumpo** [RomSteady/RomTerraria#1] opened 2016-07-12 20:14 UTC
RomTerraria works great for me but stuff doesn't scale. I have to look really close to my moitor to be able to select stuff.

I read that there's a limitation with the game and zombie spawning at 1080p res, but still. Everything appears tiny tiny. Makes me turn away from the game.

**Comment by RomSteady** [comment] 2016-08-07 20:36
I've looked into adding in UI scaling in the past.

Unfortunately, there are two separate UI frameworks in use in the game.  The classic one, used by most of the in-game UI, and the new one, used by the pause screen.

The pause screen can be made to scale easily, and I had it mostly working at one point.  However, none of the classic UI code can easily support scaling.

That said, if someone else makes a scaling mod, RomTerraria stacks on top of other mods easily.

**Comment by HawaiiBeach** [comment] 2016-08-07 21:28
:/ well I cannot play Terraria like this.. guess I'll just NOT play the game. Not only is my inventory n' stuff tiny, but placing blocks is as hard and makes my eyes start to hurt.

**Comment by RomSteady** [comment] 2016-08-13 20:21
Dug into the latest Terraria code a bit more.  I think I might be able to do some stuff piecemeal.

**Comment by RomSteady** [comment] 2016-08-13 20:57
Step 1: Inside Terraria.Main::DrawInventory(), double the value stored in inventoryScale.

![20160813135351_1](https://cloud.githubusercontent.com/assets/2880151/17645540/b6bfc748-615d-11e6-8193-0cc91da91e49.jpg)

Next, I need to find a way to detect which constants affect layout.

**Comment by RomSteady** [comment] 2016-08-13 21:23
Hopefully this screenshot will give you an idea about where this will be difficult.  Because I work at the IL layer, I can find constants, but I have no context about what they are used for.  I can double the values and write them back, but there's no guarantee that it's going to do what I want.

I'm setting it up so that I'll double certain values based on the code, but it's going to be a bit before I can say that the UI all works the way that it should.

![20160813141912_1](https://cloud.githubusercontent.com/assets/2880151/17645670/4320ba6e-6161-11e6-9c53-614310434cbb.jpg)

**Comment by RomSteady** [comment] 2016-08-13 22:18
Committed the first step in doubling the UI to ensure it doesn't get lost.  It's not working universally.  More work is definitely needed.

https://github.com/RomSteady/RomTerraria/commit/68ef3f2691f3e653df291be1665869a0b266198b

**Comment by HawaiiBeach** [comment] 2016-08-13 23:05
Nice! If you have some test builds you may link them here

**Comment by RomSteady** [comment] 2016-08-13 23:36
Will link a build as soon as I have at least the top-left inventory working at 100%.  Crafting will take significantly longer to get right.

**Comment by RomSteady** [comment] 2016-08-14 01:14
Figuring out a crash caused by replacing some LDC_I4_S opcodes with LDC_I4 opcodes.

**Comment by RomSteady** [comment] 2016-08-14 01:58
https://github.com/RomSteady/RomTerraria/commit/5785aed23809bd7d496c3ef5074f43f7b2090eef

Inventory and armor areas now properly scale.  Crafting/inventory still broken AF.

[ScalingTest1.zip](https://github.com/RomSteady/RomTerraria/files/416843/ScalingTest1.zip)

![20160813185340_1](https://cloud.githubusercontent.com/assets/2880151/17646643/b91f950c-6187-11e6-936a-876bd6b34689.jpg)

**Comment by HawaiiBeach** [comment] 2016-08-14 17:58
Yeah, inventory scales but the font doesn't, and not even mentioning other things at the side.
But progress...

**Comment by RomSteady** [comment] 2016-08-14 18:00
Font scaling will take me a bit longer after I get crafting.

What I'll have to do is iterate through the Terraria.Main::DrawInventory() method, find all the calls to draw text, step back until it pushes the font scale onto the stack, then add in a multiplier.

**Comment by RomSteady** [comment] 2016-08-14 22:24
https://github.com/RomSteady/RomTerraria/commit/9a6af2c74ee8f438d7c341d5cce600c2117d2963

Popup crafting horizontal spacing now correct, although I need to figure out how to shift it down outside of the inventory area.

![20160814152125_1](https://cloud.githubusercontent.com/assets/2880151/17652519/3648b58a-6233-11e6-83db-2e3f7b3109e3.jpg)

**Comment by HawaiiBeach** [comment] 2018-05-26 21:06
Closing - terraria now supports hidpi. (lol it has been a long time)

**Closed as completed by HawaiiBeach** 2018-05-26 21:06 UTC
